name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*.*.*'
    paths:
      - 'main.py'
      - 'requirements.txt'
      - 'Dockerfile'
      - '.github/workflows/docker-publish.yml'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            # Create a tag for the git commit hash (e.g., a1b2c3d)
            type=sha,format=short
            # Create the "latest" tag for the main branch
            type=ref,event=branch,pattern=main
            # Create a version tag when you push a git tag like "v1.2.3"
            type=semver,pattern={{version}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
